language: node_js
node_js:
 - "node"

install: npm install

before_script:
- git config --global user.name "chpmnrssll"
- git config --global user.email "chpmnrssll@gmail.com"
- sed -i "s/$GITHUB_TOKEN/${$GITHUB_TOKEN}/" _config.yml

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

cache:
  directories:
    - "node_modules"
